language: node_js
os: linux
node_js:
  - "15"

git:
  depth: 3

cache: yarn

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: "node"
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: yarn run build # do not rerun any tests
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
